import { argon2d, argon2i, argon2id } from 'hash-wasm';
import { describe, expect, test } from 'vitest';
import { ARGON2_PRESETS, matchPreset, parseHexSalt, validateParams, verifyArgon2 } from './argon2-hash.service';

// Generated with `authelia crypto hash generate argon2 --password 'test'` (Authelia v4.39.27)
const AUTHELIA_HASH =
  '$argon2id$v=19$m=65536,t=3,p=4$fWT7QpFU0VaCefehZ3i87Q$P1AQsLxVwGg1uLPKPVnC3JQir5WNjjgNSRd5+ANHiG8';

const salt = new Uint8Array(16).fill(7);
const cheap = { iterations: 1, memorySize: 64, parallelism: 1, hashLength: 32, outputType: 'encoded' } as const;

describe('argon2-hash service', () => {
  describe('ARGON2_PRESETS', () => {
    test('authelia preset matches the authelia CLI defaults', () => {
      expect(ARGON2_PRESETS.authelia).toEqual({
        variant: 'argon2id',
        iterations: 3,
        memorySizeKB: 65536,
        parallelism: 4,
        hashLength: 32,
        saltLength: 16,
      });
    });

    test('owasp preset matches the OWASP minimum', () => {
      expect(ARGON2_PRESETS.owasp).toMatchObject({ iterations: 2, memorySizeKB: 19456, parallelism: 1 });
    });
  });

  describe('matchPreset', () => {
    test('recognizes each preset', () => {
      expect(matchPreset({ ...ARGON2_PRESETS.authelia })).toBe('authelia');
      expect(matchPreset({ ...ARGON2_PRESETS.owasp })).toBe('owasp');
    });

    test('returns custom as soon as one parameter differs', () => {
      expect(matchPreset({ ...ARGON2_PRESETS.authelia, iterations: 4 })).toBe('custom');
      expect(matchPreset({ ...ARGON2_PRESETS.authelia, variant: 'argon2i' })).toBe('custom');
      expect(matchPreset({ ...ARGON2_PRESETS.authelia, saltLength: 32 })).toBe('custom');
    });
  });

  describe('parseHexSalt', () => {
    test('parses valid hex, with or without 0x prefix', () => {
      expect(parseHexSalt('0011223344556677')).toEqual(new Uint8Array([0, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77]));
      expect(parseHexSalt('0xAABBCCDDEEFF0011')).toHaveLength(8);
    });

    test('rejects non-hex, odd length and out-of-range sizes', () => {
      expect(parseHexSalt('zz11223344556677')).toBeUndefined();
      expect(parseHexSalt('0011223344556677a')).toBeUndefined();
      expect(parseHexSalt('00112233')).toBeUndefined();
      expect(parseHexSalt('00'.repeat(65))).toBeUndefined();
      expect(parseHexSalt('')).toBeUndefined();
    });
  });

  describe('validateParams', () => {
    test('authelia preset is valid without warnings', () => {
      expect(validateParams(ARGON2_PRESETS.authelia)).toEqual({ errors: [], warnings: [] });
    });

    test('memory must be at least 8 x parallelism', () => {
      const { errors } = validateParams({ ...ARGON2_PRESETS.authelia, memorySizeKB: 16, parallelism: 4 });
      expect(errors).toEqual([{ kind: 'memory-too-low', min: 32 }]);
    });

    test('memory above 1 GiB is refused', () => {
      const { errors } = validateParams({ ...ARGON2_PRESETS.authelia, memorySizeKB: 1048577 });
      expect(errors).toEqual([{ kind: 'memory-too-high', max: 1048576 }]);
    });

    test('memory above 256 MiB only warns', () => {
      const result = validateParams({ ...ARGON2_PRESETS.authelia, memorySizeKB: 262145 });
      expect(result.errors).toEqual([]);
      expect(result.warnings).toEqual([{ kind: 'memory-high', warnAbove: 262144 }]);
    });

    test('salt length must be between 8 and 64 bytes', () => {
      expect(validateParams({ ...ARGON2_PRESETS.authelia, saltLength: 7 }).errors).toEqual([
        { kind: 'salt-length-out-of-range', min: 8, max: 64 },
      ]);
      expect(validateParams({ ...ARGON2_PRESETS.authelia, saltLength: 65 }).errors).toHaveLength(1);
      expect(validateParams({ ...ARGON2_PRESETS.authelia, saltLength: 64 }).errors).toEqual([]);
    });

    test('an invalid hex salt is an error, a valid one overrides salt length', () => {
      expect(validateParams(ARGON2_PRESETS.authelia, 'not-hex').errors).toEqual([
        { kind: 'invalid-hex-salt', min: 8, max: 64 },
      ]);
      expect(validateParams({ ...ARGON2_PRESETS.authelia, saltLength: 1 }, '0011223344556677').errors).toEqual([]);
    });

    test('a cleared number field is an error', () => {
      expect(validateParams({ ...ARGON2_PRESETS.authelia, iterations: null }).errors).toEqual([
        { kind: 'missing-value' },
      ]);
    });
  });

  describe('verifyArgon2', () => {
    test('matches a hash generated by the authelia CLI', async () => {
      expect(await verifyArgon2('test', AUTHELIA_HASH)).toBe('match');
      expect(await verifyArgon2('wrong', AUTHELIA_HASH)).toBe('no-match');
    });

    test('ignores surrounding whitespace in the hash', async () => {
      expect(await verifyArgon2('test', `  ${AUTHELIA_HASH}\n`)).toBe('match');
    });

    test.each([
      ['argon2id', argon2id],
      ['argon2i', argon2i],
      ['argon2d', argon2d],
    ])('round-trips %s', async (variant, fn) => {
      const hash = await fn({ ...cheap, password: 'secret', salt });
      expect(hash.startsWith(`$${variant}$v=19$m=64,t=1,p=1$`)).toBe(true);
      expect(await verifyArgon2('secret', hash)).toBe('match');
      expect(await verifyArgon2('other', hash)).toBe('no-match');
    });

    test('rejects hashes that are not argon2 PHC strings', async () => {
      expect(await verifyArgon2('abc', '$2a$05$FHzYelm8Qn.IhGP.N8V1TOWFlRTK.8cphbxZSvSFo9B6HGscnQdhy')).toBe('invalid');
      expect(await verifyArgon2('abc', 'hello world')).toBe('invalid');
      expect(await verifyArgon2('abc', '$argon2id$v=19$m=65536,t=3,p=4$!!!$???')).toBe('invalid');
    });

    test('rejects hashes with an absurd memory cost without running them', async () => {
      const huge = AUTHELIA_HASH.replace('m=65536', 'm=4194304');
      expect(await verifyArgon2('test', huge)).toBe('invalid');
    });
  });
});
